### PR TITLE
Jupyter_french

### PR DESCRIPTION
**Pull request by oussou-dev**
French translation of course materials

### CODE REVIEW

**Comment by Yorko** [comment]
@oussou-dev Thanks for this initiative. Do you plan to translate all topics and demo assignments?

**Comment by oussou-dev** [comment]
Yes, I intend to translate all the articles as I progress in my learning.

**Comment by Yorko** [comment]
it's a big commitment. Though sure, I'll merge this PR right away. 
We can discuss progress privately on Slack (@ yorko).

**Comment by Yorko** [comment]
Though it's better to translate not only assignments but articles as well :)

**Pull request merged**
