### PR TITLE
Add assignment2_part1_decision_trees-fr_def.ipynb

### PR DESCRIPTION
**Pull request by oussou-dev**
assignment2_part1_decision_trees-fr_def.ipynb

### CODE REVIEW

**Comment by Yorko** [comment]
Thanks! 

Need to say, that I don't plan to leave full versions of assignments in this repository. So I'll merge this of course, but pls go on only with demo assignments.

**Comment by oussou-dev** [comment]
Thank you for the precision
For future translations: demo, articles and tutorials

**Comment by Yorko** [comment]
Articles and demo assignments, I suppose. Translating tutorials is too much work. Though I can select a bunch of some 5-7 really good ones, and we you translate only those.

**Comment by oussou-dev** [comment]
good proposal !
let's do this way

**Pull request merged**
