### PR TITLE
Natalia Domozhirova Tutorial fixed v3

### PR DESCRIPTION
**Pull request by dnn37**

### CODE REVIEW

**Comment by dnn37** [comment]
Please use v4

**Comment by Yorko** [comment]
You need to delete all unnecessary files and name the right one http://nbviewer.jupyter.org/github/Yorko/mlcourse.ai/blob/master/jupyter_english/tutorials/Keras_easy_way_to_construct_the_Neural_Networks_fixed.ipynb because you can't edit slack message anymore

**Comment by dnn37** [comment]
ok, will do, thank you

**Comment by dnn37** [comment]
Changed back the name and deleted the rest 

>Пятница, 14 декабря 2018, 23:11 +03:00 от Yury Kashnitskiy <notifications@github.com>:
>
>You need to delete all unnecessary files and name the right one  http://nbviewer.jupyter.org/github/Yorko/mlcourse.ai/blob/master/jupyter_english/tutorials/Keras_easy_way_to_construct_the_Neural_Networks_fixed.ipynb because you can't edit slack message anymore
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

С уважением,
Наталья
dnn37@mail.ru

**Pull request closed without merging**
