### PR TITLE
Jupyter french branch

### PR DESCRIPTION
**Pull request by oussou-dev**
Add tutorials folder
Add python-data-pre-processing-handy-tips-fr_def

### CODE REVIEW

**Comment by Yorko** [comment]
Hi! Conflicts there, pls check the [diff](https://github.com/Yorko/mlcourse.ai/pull/645/files). Would you like to add more translations?

**Comment by oussou-dev** [comment]
Hello! Yes, articles [2-6-7-8-9] + some tutorials.

Le jeu. 26 déc. 2019 à 14:14, Yury Kashnitsky <notifications@github.com> a
écrit :

**Comment by Yorko** [comment]
Then please merge it first correctly with the current master. 
PS. Thanks a lot for your efforts.

**Comment by oussou-dev** [comment]
ok! as we agreed, you'll tell me the few good tutorials to be translated

Le jeu. 26 déc. 2019 à 15:03, Yury Kashnitsky <notifications@github.com> a
écrit :

**Comment by oussou-dev** [comment]
Mistake
Make a pull request from 'jupyter_french' branch
instead of 'origin/jupyter_french' branch

**Pull request closed without merging**
